type: object
properties:
  reminder:
    type: boolean
  cache:
    type: object
    properties:
      enable:
        type: boolean
  minify:
    type: boolean
  custom_file_path:
    anyOf:
    - type: 'null'
    - type: object
      additionalProperties:
        type: string
  favicon:
    type: object
    properties:
      small:
        type: string
      medium:
        type: string
      apple_touch_icon:
        type: string
      safari_pinned_tab:
        type: string
      android_manifest:
        type: string
      ms_browserconfig:
        type: string
  language_switcher:
    type: boolean
  footer:
    type: object
    properties:
      icon:
        type: object
        properties:
          name:
            type: string
          animated:
            type: boolean
          color:
            type: string
      copyright:
        anyOf:
        - type: 'null'
        - type: string
      powered:
        type: boolean
      beian:
        type: object
        properties:
          enable:
            type: boolean
          icp:
            anyOf:
            - type: 'null'
            - type: string
          gongan_id:
            anyOf:
            - type: 'null'
            - type: string
          gongan_num:
            anyOf:
            - type: 'null'
            - type: string
          gongan_icon_url:
            anyOf:
            - type: 'null'
            - type: string
  creative_commons:
    type: object
    properties:
      license:
        type: string
      sidebar:
        type: boolean
      post:
        type: boolean
      language:
        anyOf:
        - type: 'null'
        - type: string
  scheme:
    type: string
  darkmode:
    type: boolean
  menu:
    anyOf:
    - type: 'null'
    - type: object
      additionalProperties:
        type: string
  menu_settings:
    type: object
    properties:
      icons:
        type: boolean
      badges:
        type: boolean
  sidebar:
    type: object
    properties:
      position:
        type: string
      display:
        type: string
      padding:
        type: number
      offset:
        type: number
      onmobile:
        type: boolean
  avatar:
    type: object
    properties:
      url:
        anyOf:
        - type: 'null'
        - type: string
      rounded:
        type: boolean
      rotated:
        type: boolean
  site_state:
    type: boolean
  social:
    anyOf:
    - type: 'null'
    - type: object
      additionalProperties:
        type: string
  social_icons:
    type: object
    properties:
      enable:
        type: boolean
      icons_only:
        type: boolean
      transition:
        type: boolean
  links_settings:
    type: object
    properties:
      icon:
        type: string
      title:
        type: string
      layout:
        type: string
  links:
    anyOf:
    - type: 'null'
    - type: object
      additionalProperties:
        type: string
  toc:
    type: object
    properties:
      enable:
        type: boolean
      number:
        type: boolean
      wrap:
        type: boolean
      expand_all:
        type: boolean
      max_depth:
        type: number
  chat:
    type: object
    properties:
      enable:
        type: boolean
      service:
        type: string
      icon:
        type: string
      text:
        type: string
  excerpt_description:
    type: boolean
  read_more_btn:
    type: boolean
  post_meta:
    type: object
    properties:
      item_text:
        type: boolean
      created_at:
        type: boolean
      updated_at:
        type: object
        properties:
          enable:
            type: boolean
          another_day:
            type: boolean
      categories:
        type: boolean
  symbols_count_time:
    type: object
    properties:
      separated_meta:
        type: boolean
      item_text_post:
        type: boolean
      item_text_total:
        type: boolean
  tag_icon:
    type: boolean
  reward_settings:
    type: object
    properties:
      enable:
        type: boolean
      animation:
        type: boolean
      comment:
        type: string
  reward:
    anyOf:
    - type: 'null'
    - type: object
      additionalProperties:
        type: string
  follow_me:
    anyOf:
    - type: 'null'
    - type: object
      additionalProperties:
        type: string
  related_posts:
    type: object
    properties:
      enable:
        type: boolean
      title:
        anyOf:
        - type: 'null'
        - type: string
      display_in_home:
        type: boolean
      params:
        type: object
        properties:
          maxCount:
            type: number
          PPMixingRate:
            type: number
          isDate:
            type: boolean
          isImage:
            type: boolean
          isExcerpt:
            type: boolean
  post_edit:
    type: object
    properties:
      enable:
        type: boolean
      url:
        type: string
  post_navigation:
    type: string
  tagcloud:
    type: object
    properties:
      min:
        type: number
      max:
        type: number
      amount:
        type: number
      orderby:
        type: string
      order:
        type: number
  calendar:
    type: object
    properties:
      calendar_id:
        type: string
      api_key:
        type: string
      orderBy:
        type: string
      offsetMax:
        type: number
      offsetMin:
        type: number
      showDeleted:
        type: boolean
      singleEvents:
        type: boolean
      maxResults:
        type: number
  text_align:
    type: object
    properties:
      desktop:
        type: string
      mobile:
        type: string
  mobile_layout_economy:
    type: boolean
  android_chrome_color:
    type: string
  custom_logo:
    anyOf:
    - type: 'null'
    - type: string
  codeblock:
    type: object
    properties:
      theme:
        type: object
        properties:
          light:
            type: string
          dark:
            type: string
      copy_button:
        type: object
        properties:
          enable:
            type: boolean
          show_result:
            type: boolean
          style:
            anyOf:
            - type: 'null'
            - type: string
  back2top:
    type: object
    properties:
      enable:
        type: boolean
      sidebar:
        type: boolean
      scrollpercent:
        type: boolean
  reading_progress:
    type: object
    properties:
      enable:
        type: boolean
      position:
        type: string
      color:
        type: string
      height:
        type: string
  bookmark:
    type: object
    properties:
      enable:
        type: boolean
      color:
        type: string
      save:
        type: string
  github_banner:
    type: object
    properties:
      enable:
        type: boolean
      permalink:
        type: string
      title:
        type: string
  font:
    type: object
    properties:
      enable:
        type: boolean
      host:
        anyOf:
        - type: 'null'
        - type: string
      global:
        type: object
        properties:
          external:
            type: boolean
          family:
            type: string
          size:
            anyOf:
            - type: 'null'
            - type: string
            - type: number
      title:
        type: object
        properties:
          external:
            type: boolean
          family:
            anyOf:
            - type: 'null'
            - type: string
          size:
            anyOf:
            - type: 'null'
            - type: string
            - type: number
      headings:
        type: object
        properties:
          external:
            type: boolean
          family:
            anyOf:
            - type: 'null'
            - type: string
          size:
            anyOf:
            - type: 'null'
            - type: string
            - type: number
      posts:
        type: object
        properties:
          external:
            type: boolean
          family:
            anyOf:
            - type: 'null'
            - type: string
      codes:
        type: object
        properties:
          external:
            type: boolean
          family:
            anyOf:
            - type: 'null'
            - type: string
  disable_baidu_transformation:
    type: boolean
  index_with_subtitle:
    type: boolean
  exturl:
    type: boolean
  google_site_verification:
    anyOf:
    - type: 'null'
    - type: string
    - type: number
  bing_site_verification:
    anyOf:
    - type: 'null'
    - type: string
    - type: number
  yandex_site_verification:
    anyOf:
    - type: 'null'
    - type: string
    - type: number
  baidu_site_verification:
    anyOf:
    - type: 'null'
    - type: string
    - type: number
  baidu_push:
    type: boolean
  math:
    type: object
    properties:
      per_page:
        type: boolean
      mathjax:
        type: object
        properties:
          enable:
            type: boolean
          mhchem:
            type: boolean
      katex:
        type: object
        properties:
          enable:
            type: boolean
          copy_tex:
            type: boolean
  pjax:
    type: boolean
  fancybox:
    type: boolean
  mediumzoom:
    type: boolean
  lazyload:
    type: boolean
  pangu:
    type: boolean
  quicklink:
    type: object
    properties:
      enable:
        type: boolean
      home:
        type: boolean
      archive:
        type: boolean
      delay:
        type: boolean
      timeout:
        type: number
      priority:
        type: boolean
      ignores:
        anyOf:
        - type: 'null'
        - type: string
        - type: number
        - type: array
  comments:
    type: object
    properties:
      style:
        type: string
      active:
        anyOf:
        - type: 'null'
        - type: string
      storage:
        type: boolean
      lazyload:
        type: boolean
      nav:
        anyOf:
        - type: 'null'
        - type: object
  disqus:
    type: object
    properties:
      enable:
        type: boolean
      shortname:
        anyOf:
        - type: 'null'
        - type: string
      count:
        type: boolean
  disqusjs:
    type: object
    properties:
      enable:
        type: boolean
      api:
        anyOf:
        - type: 'null'
        - type: string
      apikey:
        anyOf:
        - type: 'null'
        - type: string
      shortname:
        anyOf:
        - type: 'null'
        - type: string
  changyan:
    type: object
    properties:
      enable:
        type: boolean
      appid:
        anyOf:
        - type: 'null'
        - type: string
      appkey:
        anyOf:
        - type: 'null'
        - type: string
  valine:
    type: object
    properties:
      enable:
        type: boolean
      appId:
        anyOf:
        - type: 'null'
        - type: string
      appKey:
        anyOf:
        - type: 'null'
        - type: string
      placeholder:
        type: string
      avatar:
        type: string
      meta:
        type: array
        items:
          type: string
      pageSize:
        type: number
      language:
        anyOf:
        - type: 'null'
        - type: string
      visitor:
        type: boolean
      comment_count:
        type: boolean
      recordIP:
        type: boolean
      serverURLs:
        anyOf:
        - type: 'null'
        - type: string
  livere_uid:
    type: 'null'
  gitalk:
    type: object
    properties:
      enable:
        type: boolean
      github_id:
        anyOf:
        - type: 'null'
        - type: string
      repo:
        anyOf:
        - type: 'null'
        - type: string
      client_id:
        anyOf:
        - type: 'null'
        - type: string
      client_secret:
        anyOf:
        - type: 'null'
        - type: string
      admin_user:
        anyOf:
        - type: 'null'
        - type: string
      distraction_free_mode:
        type: boolean
      language:
        anyOf:
        - type: 'null'
        - type: string
  rating:
    type: object
    properties:
      enable:
        type: boolean
      id:
        anyOf:
        - type: 'null'
        - type: string
      color:
        type: string
  add_this_id:
    anyOf:
    - type: 'null'
    - type: string
  google_analytics:
    type: object
    properties:
      tracking_id:
        anyOf:
        - type: 'null'
        - type: string
      only_pageview:
        type: boolean
  baidu_analytics:
    anyOf:
    - type: 'null'
    - type: string
  growingio_analytics:
    anyOf:
    - type: 'null'
    - type: string
  cnzz_siteid:
    anyOf:
    - type: 'null'
    - type: string
  leancloud_visitors:
    type: object
    properties:
      enable:
        type: boolean
      app_id:
        anyOf:
        - type: 'null'
        - type: string
      app_key:
        anyOf:
        - type: 'null'
        - type: string
      server_url:
        anyOf:
        - type: 'null'
        - type: string
      security:
        type: boolean
  firestore:
    type: object
    properties:
      enable:
        type: boolean
      collection:
        type: string
      apiKey:
        anyOf:
        - type: 'null'
        - type: string
      projectId:
        anyOf:
        - type: 'null'
        - type: string
  busuanzi_count:
    type: object
    properties:
      enable:
        type: boolean
      total_visitors:
        type: boolean
      total_visitors_icon:
        type: string
      total_views:
        type: boolean
      total_views_icon:
        type: string
      post_views:
        type: boolean
      post_views_icon:
        type: string
  algolia_search:
    type: object
    properties:
      enable:
        type: boolean
      hits:
        type: object
        properties:
          per_page:
            type: number
      labels:
        type: object
        properties:
          input_placeholder:
            type: string
          hits_empty:
            type: string
          hits_stats:
            type: string
  local_search:
    type: object
    properties:
      enable:
        type: boolean
      trigger:
        type: string
      top_n_per_article:
        type: number
      unescape:
        type: boolean
      preload:
        type: boolean
  swiftype_key:
    anyOf:
    - type: 'null'
    - type: string
  chatra:
    type: object
    properties:
      enable:
        type: boolean
      async:
        type: boolean
      id:
        anyOf:
        - type: 'null'
        - type: string
  tidio:
    type: object
    properties:
      enable:
        type: boolean
      key:
        anyOf:
        - type: 'null'
        - type: string
  note:
    type: object
    properties:
      style:
        type: string
      icons:
        type: boolean
      light_bg_offset:
        type: number
  tabs:
    type: object
    properties:
      transition:
        type: object
        properties:
          tabs:
            type: boolean
          labels:
            type: boolean
  pdf:
    type: object
    properties:
      enable:
        type: boolean
      height:
        type: string
  mermaid:
    type: object
    properties:
      enable:
        type: boolean
      theme:
        type: string
  motion:
    type: object
    properties:
      enable:
        type: boolean
      async:
        type: boolean
      transition:
        type: object
        properties:
          post_block:
            type: string
          post_header:
            type: string
          post_body:
            type: string
          coll_header:
            type: string
          sidebar:
            type: string
  pace:
    type: object
    properties:
      enable:
        type: boolean
      theme:
        type: string
  three:
    type: object
    properties:
      enable:
        type: boolean
      three_waves:
        type: boolean
      canvas_lines:
        type: boolean
      canvas_sphere:
        type: boolean
  canvas_ribbon:
    type: object
    properties:
      enable:
        type: boolean
      size:
        type: number
      alpha:
        type: number
      zIndex:
        type: number
  vendors:
    type: object
    properties:
      _internal:
        type: string
      anime:
        anyOf:
        - type: 'null'
        - type: string
      fontawesome:
        anyOf:
        - type: 'null'
        - type: string
      mathjax:
        anyOf:
        - type: 'null'
        - type: string
      katex:
        anyOf:
        - type: 'null'
        - type: string
      copy_tex_js:
        anyOf:
        - type: 'null'
        - type: string
      copy_tex_css:
        anyOf:
        - type: 'null'
        - type: string
      pjax:
        anyOf:
        - type: 'null'
        - type: string
      jquery:
        anyOf:
        - type: 'null'
        - type: string
      fancybox:
        anyOf:
        - type: 'null'
        - type: string
      fancybox_css:
        anyOf:
        - type: 'null'
        - type: string
      mediumzoom:
        anyOf:
        - type: 'null'
        - type: string
      lazyload:
        anyOf:
        - type: 'null'
        - type: string
      pangu:
        anyOf:
        - type: 'null'
        - type: string
      quicklink:
        anyOf:
        - type: 'null'
        - type: string
      disqusjs_js:
        anyOf:
        - type: 'null'
        - type: string
      disqusjs_css:
        anyOf:
        - type: 'null'
        - type: string
      valine:
        anyOf:
        - type: 'null'
        - type: string
      gitalk_js:
        anyOf:
        - type: 'null'
        - type: string
      gitalk_css:
        anyOf:
        - type: 'null'
        - type: string
      algolia_search:
        anyOf:
        - type: 'null'
        - type: string
      instant_search:
        anyOf:
        - type: 'null'
        - type: string
      mermaid:
        anyOf:
        - type: 'null'
        - type: string
      velocity:
        anyOf:
        - type: 'null'
        - type: string
      velocity_ui:
        anyOf:
        - type: 'null'
        - type: string
      pace:
        anyOf:
        - type: 'null'
        - type: string
      pace_css:
        anyOf:
        - type: 'null'
        - type: string
      three:
        anyOf:
        - type: 'null'
        - type: string
      three_waves:
        anyOf:
        - type: 'null'
        - type: string
      canvas_lines:
        anyOf:
        - type: 'null'
        - type: string
      canvas_sphere:
        anyOf:
        - type: 'null'
        - type: string
      canvas_ribbon:
        anyOf:
        - type: 'null'
        - type: string
  css:
    type: string
  js:
    type: string
  images:
    type: string
